### ISSUE TITLE
Link to AppControl feature of SD Maid

### ISSUE THREAD

**Issue by TheMysticS** [d4rken-org/permission-pilot#103]
Can you allow this app to launch the **AppControl** section of SD Maid with the press of a button from the Apps Tab?

If SD Maid is not installed, the button will show a prompt that SD Maid is required for this feature, with a direct link to SD Maid page on Google Play Store.

You can include this shortcut either next to the Refresh button or inside the overflow menu on top right.

The AppControl feature of SD Maid is pretty useful and would complement this app. Remember, I asked you if that can be integrated with this app, and you told me it requires a lot of code work? This is a good alternative to that.

**Comment by d4rken** [comment]
Thought about it and I do not want to have to keep compatibility between SD Maid and this app.

**Comment by TheMysticS** [comment]
That's fine.

But didn't get the compatibility part. This is just a shortcut, isn't it?

**Comment by d4rken** [comment]
A shortcut can be different things.
* Intent with just a component name if the feature has it's own activity
* A specific intent action that the app supports
* Deep navigation with URIs if never androidX navigation is used

We also have to consider how data is passed, should something happen? Data loaded, specific app filtered?
Handle edge-cases if SD Maid is loaded or not, if setup has been done, if currently work is on-going etc.
If something is on-going, do we save it somewhere, does it survive rotation? What happens if multiple "shortcuts" are executed.

A quick solution creates a stronger relation ship between both apps and when changing either one, it's something that has to be thought about, so higher maintenance effort. A not quick solution isn't so easy to break but requires significantly more effort to implement. So it's either high upfront cost, or high on-going cost.

**Comment by TheMysticS** [comment]
The shortcut I'm referring to will just 'open' the AppControl page in SD Maid. It won't do anything of its own. If AppControl is already running (which is very unlikely), the existing operation will continue. 

This won't be a shortcut that will 'execute' something. It's more like a launcher icon that just opens a specific section within the app. Nothing more.
