### ISSUE TITLE
Self-diagnosis shows INTERNET permission for Permission Pilot

### ISSUE THREAD

**Issue by fe60** [d4rken-org/permission-pilot#190]
The self-diagnosis of Permission Pilot says, it has the permission to have full network access, whereas the Welcome screen, the privacy policy and the Manifest file say it has not.

Where does the contradiction come from?

### Self-diagnosis showing INTERNET permission
<image width="200" src="https://github.com/d4rken-org/permission-pilot/assets/31078918/9e97c0e1-6778-42c8-a33d-f9f67a30e547" />

### Manifest, privacy policy, welcome screen
https://github.com/d4rken-org/permission-pilot/blob/36414126fd8b748653903365f57d7d6f722f6ad9/app/src/main/AndroidManifest.xml#L5-L10

https://github.com/d4rken-org/permission-pilot/blob/36414126fd8b748653903365f57d7d6f722f6ad9/PRIVACY_POLICY.md?plain=1#L7

https://github.com/d4rken-org/permission-pilot/blob/36414126fd8b748653903365f57d7d6f722f6ad9/app/src/main/res/values/strings.xml#L263

**Comment by d4rken** [comment]
Hm, good question :thinking: Is it the Google Play billing dependency doing this?

**Comment by d4rken** [comment]
The permission is added by the dependency:

```
com.google.android.datatransport:transport-backend-cct
```

which is pulled in by the Google Play billing SDK:

```
+--- com.android.billingclient:billing:6.0.1
|    +--- com.google.android.datatransport:transport-api:3.0.0
|    |    \--- androidx.annotation:annotation:1.1.0 -> 1.4.0 (*)
|    +--- com.google.android.datatransport:transport-backend-cct:3.1.8
```

**Comment by d4rken** [comment]
Sneaky Google :roll_eyes:.
I think it makes sense, but I also thought that it wouldn't need this as it would never query the network correctly, because the client library only ever binds to Google Services and communicates through that.

So "no internet" only holds true for the FOSS build.

I'm tempted to just remove the billing library, but the app makes a little money which is nice to keep working on it.

So let's adjust the text to not lie.

**Comment by Fertewwqkc** [comment]
Oh my god 🫣 i never dowmload an app from an other app except tonight 🥱🥱 thank you so much
