### ISSUE TITLE
App Store Link

### ISSUE THREAD

**Issue by TheMysticS** [d4rken-org/permission-pilot#82]
In the Apps tab, the install source icon is shown for each app on the right.

Where the install source is Google Play Store or an OEM Store, please make that icon clickable to launch the app page in the respective store.

**Comment by d4rken** [comment]
This already happens when you click the installer source text. Do you want to change that?
Icon to play store, text to app details, or vice versa?

**Comment by TheMysticS** [comment]
I mean on the Apps Tab where we show the install source on right. That icon is currently not clickable. It would be nice to have that icon act as a direct link to the app page on the respective Store.

On the App Details page, if the installer source is Google Play Store or OEM Store, clicking on the icon should open the app page in the Store, to maintain consistency with above.

**Comment by TheMysticS** [comment]
No support for apps installed from OEM Stores?

**Comment by d4rken** [comment]
Can be added (new tickets) if you tell me how to generate the correct URL:

https://github.com/d4rken-org/permission-pilot/blob/afed4b519b37a2fcd6a90c4b3854b6e62d60dfcf/app/src/main/java/eu/darken/myperm/apps/core/known/AKnownPkg.kt#L22-L28

**Comment by TheMysticS** [comment]
The direct links are already available in the App Info page in System Settings. Can you not pick it up from there?

**Comment by dragonGod97677** [comment]
Google play store app links works to Oppo App Market.

I know oppo app market does have own link but i cant copy the latest apk version that has been installed to my device (Oppo A3s), so that, i can check the AndroidManifest.xml file. It seems oppo puts the apk elsewhere, not on the /data/app/ anymore. Which is suspicious for me.

SD Maid, doesn't see latest app market, same as for Permission Pilot.
MiXplorer and [My Apk](https://play.google.com/store/apps/details?id=com.andatsoft.myapk.fwa) too.

And the latest apk version installed for my device is 
![Screenshot_2022-07-27-19-40-16-97](https://user-images.githubusercontent.com/38875906/181238093-f3b5fa73-a9fb-4f7e-bc86-f4cbdc67a9be.png)

And the old apk version that has bundled on my device, on it's AndroidManifest.xml, doesn't show anything that it's supports opening google play store links but technically, it does support

**Comment by dragonGod97677** [comment]
As for vivo V-AppStore, it supports google play store app links too but i don't exactly know if it does have own links that you can use to open to a browser and redirect to V-AppStore

**Comment by dragonGod97677** [comment]
As for Huawei, i don't know if it still supports google play store app links.

Here's the link https://appgallery.huawei.com/app/C100130495

That app is TikTok, and Huawei doesn't use app Package names for the links

**Comment by TheMysticS** [comment]
>Google play store app links works to Oppo App Market.
>
I think Color OS is somehow hijacking Google Play Store links to open in its own Store. On my Samsung phone, Google Play Store links are working perfectly fine.

**Comment by d4rken** [comment]
This is the code that triggers when you click the Store info in the system settings:

![Screenshot from 2022-07-27 14-04-33](https://user-images.githubusercontent.com/1439229/181242494-35e3366d-ce3e-462a-a5b2-758537b9def7.png)


https://cs.android.com/android/platform/superproject/+/master:packages/apps/Settings/src/com/android/settings/applications/appinfo/AppInstallerInfoPreferenceController.java;l=60?q=app_install_details_summary&ss=android%2Fplatform%2Fsuperproject:packages%2Fapps%2FSettings%2F

They use a special intent `ACTION_SHOW_APP_INFO`:
https://developer.android.com/reference/android/content/Intent#ACTION_SHOW_APP_INFO

API 24 only though...

https://cs.android.com/android/platform/superproject/+/master:packages/apps/Settings/src/com/android/settings/applications/AppStoreUtil.java;l=66-76;drc=ae472b6822fddee53551ba19a0488b21f3fc92fd

**Comment by d4rken** [comment]
I've implement the way google does it, with fallback (unable to resolve or Android 5-7 i) to the urlGenerator pattern as mentioned here:
https://github.com/d4rken-org/permission-pilot/issues/82#issuecomment-1195645377
